# Setup
title:        'ارائه آردوآینو'
tagline:      'برای کلاس ریزپردازنده'
baseurl:      "/arduino"
paginate:     1

# About/contact
author:
  name:       'محسن دستجردی زاده'
  url:        https://mehsen.com 

# Gems
gems:
  - jekyll-paginate
  - jekyll-seo-tag
 
#Others
markdown: kramdown