# Setup
title:        'آردوآینو'
tagline:      'ارائه برای کلاس ریزپردازنده'
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       'محسن دستجردی زاده'
  url:        https://mehsen.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown